namespace UnityIceFebruary.HelpTools.AutoGenerator
{
    using IceFebruary;
    using IceFebruary.Proxy;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Text;
    using UnityIceFebruary.HelpTools.Debuggers;

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static class ProxyCodeBuilder
    {
        [EditorBrowsable(EditorBrowsableState.Never)]
        public static string GetInterfaceProxyCode(Type type)
        {
            StringBuilder stringBuilder = new();

            stringBuilder.SetAutogeneratedMark();

            stringBuilder.AppendLine($"public interface {type.GetProxyName()}");
            stringBuilder.AppendLine("{");
            stringBuilder.AppendLine($"    public {type.FullName} ToPoco();");
            stringBuilder.AppendLine("}");

            return stringBuilder.ToString();
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public static string GetFieldProxyCode(Type type, FieldProxy fieldProxy)
        {
            StringBuilder stringBuilder = new();

            stringBuilder.SetAutogeneratedMark();

            stringBuilder.AppendLine("[System.Serializable]");
            stringBuilder.Append($"public sealed class {type.GetProxyName()}");

            Type fieldProxyInterface = fieldProxy.InterfaceType;
            bool fieldProxyInterfaceExists = fieldProxyInterface != null;

            if (fieldProxyInterfaceExists && !fieldProxyInterface.HasAttribute<InterfaceProxy>())
            {
                stringBuilder.AppendLine($" {{ }} //{ProxyGenerator.TroubleMark}");

                ProxyGeneratorDebugger.WarnAboutUnproxyableObject();

                return stringBuilder.ToString();
            }

            stringBuilder.AppendLine(fieldProxyInterfaceExists ? $" : {fieldProxyInterface.GetProxyName()}" : string.Empty);

            if (type.IsUnityBaseEntity(out Type unityType))
                stringBuilder.SetUnityComponentBody(unityType, fieldProxyInterface);
            else
                stringBuilder.SetAverageBody(type, fieldProxy.InterfaceType);

            return stringBuilder.ToString();
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public static string GetDataObjectProxyCode(Type type)
        {
            StringBuilder stringBuilder = new();

            stringBuilder.SetAutogeneratedMark();

            stringBuilder.AppendLine($"[UnityEngine.CreateAssetMenu(fileName = \"{type.Name}\", menuName = \"Proxy/{type.Name}\")]");
            stringBuilder.AppendLine($"public sealed class {type.GetProxyName()} : UnityEngine.ScriptableObject");
            stringBuilder.SetAverageBody(type);

            return stringBuilder.ToString();
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public static string GetGenericVariantProxyCode(Type type)
        {
            StringBuilder stringBuilder = new();

            stringBuilder.SetAutogeneratedMark();

            stringBuilder.AppendLine("[System.Serializable]");
            stringBuilder.AppendLine($"public sealed class {type.GetGenericProxyName()}");

            stringBuilder.SetAverageBody(type);

            return stringBuilder.ToString();
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public static string GetProxyCode(Type type)
        {
            StringBuilder stringBuilder = new();

            stringBuilder.SetAutogeneratedMark();

            stringBuilder.AppendLine($"public sealed class {type.GetProxyName()} : UnityIceFebruary.UnityInfo");
            stringBuilder.SetAverageBody(type, typeof(IRootConfig), "override");

            return stringBuilder.ToString();
        }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public static string GetUnityMatchComponentCode(IEnumerable<string> pairs)
        {
            StringBuilder stringBuilder = new();

            stringBuilder.SetAutogeneratedMark();

            stringBuilder.AppendLine($"public static class {ProxyGenerator.UnityMatchObjectsName}");
            stringBuilder.AppendLine("{");
            stringBuilder.AppendLine("    public static readonly System.Collections.Generic.Dictionary<System.Type, System.Func<UnityEngine.Object, IceFebruary.IBaseEntity>> FabricAliases = new()");
            stringBuilder.AppendLine("    {");
            stringBuilder.AppendLine(string.Join(",\n", pairs));
            stringBuilder.AppendLine("    };");
            stringBuilder.AppendLine("}");

            return stringBuilder.ToString();
        }
    }
}
