namespace UnityIceFebruary.HelpTools.AutoGenerator
{
    using IceFebruary.Proxy;
    using System;
    using System.IO;
    using System.Linq;
    using System.Reflection;
    using UnityEditor;
    using UnityIceFebruary.HelpTools.Debuggers;

    public static class ProxyGenerator
    {
        public const string AutogeneratedMark = "AUTOGENERATED";
        public const string TroubleMark = "TROUBLES";

        [MenuItem("Tools/Generate scripts")]
        public static void Generate()
        {
            ProxyDirectory.RecoveryDirectories();

            Type[] inGameTypes = Assembly.Load("Assembly-CSharp").GetTypes()
                .Where(type => !type.Name.EndsWith(AutogeneratedMark))
                .ToArray();

            Type[] proxyableTypes = inGameTypes
                .Where(type => type.IsProxyable())
                .OrderBy(type => GetPriority(type))
                .ToArray();

            if (proxyableTypes.Length == 0)
            {
                ProxyGeneratorDebugger.WarnAboutProxyableAbsence();
                return;
            }

            ProxyGeneratorDebugger.DebugInformationAboutProxyableTypes(proxyableTypes);

            UnityMatchPair[] pairs = inGameTypes
                .Select<Type, UnityMatchPair?>(type => type.IsUnityBaseEntity(out Type unityType) ? new(type, unityType) : null)
                .OfType<UnityMatchPair>()
                .ToArray();

            GenerateStaticProxy(pairs);

            foreach (Type type in proxyableTypes)
            {
                if (type.HasAttribute())
                    GenerateProxyByAttribute(type);
                if (type.IsConfig())
                    GenerateConfigProxy(type);
            }

            ProxyGeneratorDebugger.DebugSuccess();

            AssetDatabase.Refresh();
        }
        private static void GenerateProxyByAttribute(Type type)
        {
            GeneratorAttribute attribute = type.GetAttribute<GeneratorAttribute>();

            (Type attributeType, string code) = attribute switch
            {
                FieldProxy fieldProxy => (typeof(FieldProxy), ProxyCodeBuilder.GetFieldProxyCode(type, fieldProxy)),
                InterfaceProxy => (typeof(InterfaceProxy), ProxyCodeBuilder.GetInterfaceProxyCode(type)),
                ScriptableObjectProxy => (typeof(ScriptableObjectProxy), ProxyCodeBuilder.GetScriptableObjectProxyCode(type)),
                _ => (null, null)
            };

            Generate(attributeType, type.GetProxyName(), code);
        }
        private static void GenerateConfigProxy(Type type) => Generate(typeof(Proxy), type.GetProxyName(), ProxyCodeBuilder.GetProxyCode(type));
        private static void GenerateStaticProxy(UnityMatchPair[] pairs) => Generate(typeof(StaticProxy), StaticProxy.UnityMatchObjectsName, StaticProxyCodeBuilder.GetStaticUnityMatchComponentCode(pairs));
        public static void GenerateGenericVariantProxy(Type type) => Generate(typeof(GenericVariantProxy), type.GetGenericProxyName(), ProxyCodeBuilder.GetGenericVariantProxyCode(type));
        private static int GetPriority(Type type)
        {
            if (type.HasAttribute<InterfaceProxy>())
                return 1;
            return int.MaxValue;
        }
        private static void Generate(Type type, string fileName, string code)
        {
            File.WriteAllText(Path.Combine(ProxyDirectory.GetPath(type), $"{fileName}.cs"), code);

            ProxyGeneratorDebugger.DebugGeneratedProxy(fileName);
        }
    }
}
