namespace UnityIceFebruary.HelpTools.AutoGenerator
{
    using IceFebruary;
    using IceFebruary.Proxy;
    using System;
    using System.Linq;
    using System.Reflection;

    public static class ProxyTypeExtensions
    {
        private static readonly BindingFlags _flags = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static;
        public static string GetProxyName(this Type type) => $"{type.Name}_{ProxyGenerator.AutogeneratedMark}";
        public static string GetGenericProxyName(this Type type) => $"{type.Name.Split('`')[0]}_{string.Join('_', type.GetGenericArguments().Select(type => type.Name))}_{ProxyGenerator.AutogeneratedMark}";
        public static string GetGenericName(this Type type) => $"{type.FullName.Split('`')[0]}<{string.Join(", ", type.GetGenericArguments().Select(type => type.FullName))}>";
        public static T GetAttribute<T>(this Type type) where T : GeneratorAttribute
        {
            T attributeOnType = type.GetCustomAttributes<T>(true).FirstOrDefault();

            if (attributeOnType != null)
                return attributeOnType;

            return type
                .GetMembers(_flags)
                .Select(member => member.GetCustomAttributes<T>(true).FirstOrDefault())
                .FirstOrDefault(attribute => attribute != null);
        }
        public static bool HasAttribute<T>(this Type type) where T : GeneratorAttribute
        {
            if (type.IsDefined(typeof(T), true))
                return true;

            return type
                .GetMembers(_flags)
                .Any(member => member.IsDefined(typeof(T), true));
        }
        public static bool HasAttribute(this Type type) => type.HasAttribute<GeneratorAttribute>();
        public static bool IsProxyable(this Type type) => type.HasAttribute() || type.IsConfig();
        public static bool IsGenericVariant(this Type type) => type.IsGenericType && !type.IsGenericTypeDefinition && !type.ContainsGenericParameters;
        public static bool IsConfig(this Type type) => typeof(IRootConfig).IsAssignableFrom(type) && type != typeof(IRootConfig);
        public static bool IsArray(this Type type, out Type elementType)
        {
            elementType = type.GetElementType();
            return type.IsArray;
        }
        public static bool IsUnityBaseEntity(this Type type, out Type unityType)
        {
            unityType = type.BaseType;
            bool isUnityBaseEntity = unityType != null && unityType.IsGenericType && unityType.GetGenericTypeDefinition() == typeof(UnityBaseEntity<>);
            unityType = isUnityBaseEntity ? unityType.GetGenericArguments()[0] : null;
            return isUnityBaseEntity;
        }
    }
}
