namespace UnityIceFebruary.HelpTools.AutoGenerator
{
    using IceFebruary.Proxy;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.IO;
    using System.Linq;
    using System.Reflection;
    using UnityEditor;
    using UnityIceFebruary.HelpTools.Debuggers;

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static class ProxyGenerator
    {
        public const string AutogeneratedMark = "AUTOGENERATED";
        public const string TroubleMark = "TROUBLES";

        public const string UnityMatchObjectsName = "UnityMatchObject";

        [MenuItem("Tools/Generate scripts")]
        private static void Generate()
        {
            ProxyDirectory.RecoveryDirectories();

            IEnumerable<Type> inGameTypes = Assembly.Load("Assembly-CSharp").GetTypes()
                .Where(type => !type.Name.EndsWith(AutogeneratedMark));

            IEnumerable<Type> proxyableTypes = inGameTypes
                .Where(type => type.IsProxyable())
                .OrderBy(type => GetPriority(type));

            int proxyableTypesCount = proxyableTypes.Count();

            if (proxyableTypesCount == 0)
            {
                ProxyGeneratorDebugger.WarnAboutProxyableAbsence();
                return;
            }

            ProxyGeneratorDebugger.DebugInformationAboutProxyableTypes(proxyableTypesCount, proxyableTypes);

            IEnumerable<string> pairs = inGameTypes
                .Select(type => type.IsUnityBaseEntity(out Type unityType) ? type.GetMatchPair(unityType) : null)
                .Where(str => str != null);

            GenerateStaticProxy(pairs);

            foreach (Type type in proxyableTypes)
            {
                if (type.HasAttribute())
                    GenerateProxyByAttribute(type);
                if (type.IsConfig())
                    GenerateConfigProxy(type);
            }

            ProxyGeneratorDebugger.DebugSuccess();

            AssetDatabase.Refresh();
        }
        private static void GenerateProxyByAttribute(Type type)
        {
            GeneratorAttribute attribute = type.GetAttribute<GeneratorAttribute>();

            (ProxyType attributeType, string code) = attribute switch
            {
                FieldProxy fieldProxy => (ProxyType.FieldProxy, ProxyCodeBuilder.GetFieldProxyCode(type, fieldProxy)),
                InterfaceProxy => (ProxyType.InterfaceProxy, ProxyCodeBuilder.GetInterfaceProxyCode(type)),
                DataObjectProxy => (ProxyType.DataObjectProxy, ProxyCodeBuilder.GetDataObjectProxyCode(type)),
                _ => (ProxyType.None, null)
            };

            Generate(attributeType, type.GetProxyName(), code);
        }
        private static void GenerateConfigProxy(Type type) => Generate(ProxyType.Proxy, type.GetProxyName(), ProxyCodeBuilder.GetProxyCode(type));
        private static void GenerateStaticProxy(IEnumerable<string> pairs) => Generate(ProxyType.StaticProxy, UnityMatchObjectsName, ProxyCodeBuilder.GetUnityMatchComponentCode(pairs));
        [EditorBrowsable(EditorBrowsableState.Never)]
        public static void GenerateGenericVariantProxy(Type type) => Generate(ProxyType.GenericVariantProxy, type.GetGenericProxyName(), ProxyCodeBuilder.GetGenericVariantProxyCode(type));
        private static int GetPriority(Type type)
        {
            if (type.HasAttribute<InterfaceProxy>())
                return 1;
            return int.MaxValue;
        }
        private static void Generate(ProxyType type, string fileName, string code)
        {
            File.WriteAllText(Path.Combine(ProxyDirectory.GetPath(type), $"{fileName}.cs"), code);

            ProxyGeneratorDebugger.DebugGeneratedProxy(fileName);
        }
    }
}
