namespace UnityIceFebruary.HelpTools.AutoGenerator
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Reflection;
    using System.Text;

    public static class ProxyStringBuilderExtensions
    {
        public static void SetAutogeneratedMark(this StringBuilder stringBuilder) => stringBuilder.AppendLine($"//{ProxyGenerator.AutogeneratedMark}. DO NOT EDIT.");
        public static void SetUnityComponentBody(this StringBuilder stringBuilder, Type unityType, Type interfaceType)
        {
            string interfaceFullName = interfaceType.FullName;
            string unityFullName = unityType.FullName;

            stringBuilder.AppendLine("{");
            stringBuilder.AppendLine($"    [UnityEngine.SerializeField] private {unityFullName} _unityObject;");
            stringBuilder.AppendLine($"    public {interfaceFullName} ToPoco() => UnityIceFebruary.UnityMethods.Upsert<{unityFullName}, {interfaceFullName}>(_unityObject);");
            stringBuilder.AppendLine("}");
        }
        public static void SetAverageBody(this StringBuilder stringBuilder, Type type, Type toPocoType = null, string toPocoAdditionalKeys = null)
        {
            stringBuilder.AppendLine("{");

            ParameterInfo[] parameters = type
                .GetConstructors()
                .First()
                .GetParameters();

            List<string> parametersNames = new();

            foreach (ParameterInfo parameterInfo in parameters)
            {
                Type parameterType = parameterInfo.ParameterType;

                bool isArray = parameterType.IsArray(out Type elementType);

                if (!isArray)
                    elementType = parameterType;

                stringBuilder.SetField(elementType, isArray, $"_{parameterInfo.Name}", parametersNames);
            }

            stringBuilder.Append($"    public ");

            if (!string.IsNullOrWhiteSpace(toPocoAdditionalKeys))
                stringBuilder.Append($"{toPocoAdditionalKeys} ");

            string objectName = type.IsGenericVariant() ? type.GetGenericName() : type.FullName;

            stringBuilder.Append($"{(toPocoType == null ? objectName : toPocoType.FullName)} ToPoco() => new {objectName}({string.Join(", ", parametersNames)}");
            stringBuilder.AppendLine(");");
            stringBuilder.AppendLine("}");
        }
        private static void SetField(this StringBuilder stringBuilder, Type elementType, bool isArray, string fieldName, List<string> parametersNames)
        {
            stringBuilder.Append($"    [UnityEngine.{(elementType.IsInterface ? "SerializeReference, UnityIceFebruary.InterfaceImplementation.InterfaceImplementation" : "SerializeField")}] private ");

            string elementTypeName = string.Empty;

            bool isElementGenericVariant = elementType.IsGenericVariant();

            if (isElementGenericVariant)
                ProxyGenerator.GenerateGenericVariantProxy(elementType);

            if (isElementGenericVariant || elementType.IsProxyable())
            {
                elementTypeName = isElementGenericVariant ? elementType.GetGenericProxyName() : elementType.GetProxyName();
                parametersNames.Add(isArray ? $"System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Select({fieldName} ?? new {elementTypeName}[0], element => element.ToPoco()))" : $"{fieldName} == null ? default : {fieldName}.ToPoco()");
            }

            else
            {
                elementTypeName = elementType.FullName;
                parametersNames.Add(fieldName);
            }

            stringBuilder.Append(elementTypeName);

            if (isArray)
                stringBuilder.Append("[]");

            stringBuilder.AppendLine($" {fieldName};");
        }
    }
}
