namespace UnityIceFebruary.HelpTools.AutoGenerator
{
    using System.Linq;
    using System.Text;

    public static class StaticProxyCodeBuilder
    {
        public static string GetStaticUnityMatchComponentCode(UnityMatchPair[] pairs)
        {
            StringBuilder stringBuilder = new();

            stringBuilder.SetAutogeneratedMark();

            stringBuilder.AppendLine($"public static class {StaticProxy.UnityMatchObjectsName}");
            stringBuilder.AppendLine("{");
            stringBuilder.AppendLine("    public static readonly System.Collections.Generic.Dictionary<System.Type, System.Func<UnityEngine.Object, IceFebruary.IBaseEntity>> FabricAliases = new()");
            stringBuilder.AppendLine("    {");
            stringBuilder.AppendLine(string.Join(",\n", pairs.Select(pair => UnityMatchPair.GetFabricAliasesPair(pair))));
            stringBuilder.AppendLine("    };");
            stringBuilder.AppendLine("}");

            return stringBuilder.ToString();
        }
    }
}
